; Waveshare ESP32-S3-Touch-LCD-2.1B
; ESP32-S3, 8MB OPI PSRAM, 16MB Flash, CH343 USB-serial on COM6
[env:esp32s3]
; pioarduino даёт arduino-esp32 3.x (IDF 5.x) — нужно для esp_lcd RGB (num_fbs/double_fb) и ledcAttach
platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
board = esp32-s3-devkitc-1
framework = arduino

; --- порт (плата сидит на COM6) ---
upload_port = COM6
monitor_port = COM6
monitor_speed = 115200
upload_speed = 921600

; --- память этой платы ---
board_build.arduino.memory_type = qio_opi   ; 8MB OPI PSRAM
board_upload.flash_size = 16MB
board_build.partitions = partitions_16MB.csv
board_build.filesystem = littlefs

lib_deps =
    lvgl/lvgl@8.3.10
    h2zero/NimBLE-Arduino @ ^2.2.3
    bitbank2/JPEGDEC @ ^1.8.2
    bitbank2/AnimatedGIF @ ^2.2.0

build_flags =
    -DBOARD_HAS_PSRAM
    -DARDUINO_USB_CDC_ON_BOOT=0   ; Serial -> UART0 -> мост CH343 (COM6)
    -DLV_CONF_INCLUDE_SIMPLE       ; lv_conf.h лежит в include/
    -I include
