name: znachok_bmw
description: Local show editor and publisher for the Znachok ESP32-P4 display.
publish_to: 'none'
version: 3.7.0+31

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  file_picker: ^10.3.7
  permission_handler: ^11.3.1
  image: ^4.9.2
  path_provider: ^2.1.6
  uuid: ^4.6.0
  path: ^1.9.1
  crypto: ^3.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - integration_test/fixtures/android-system.mp4
