name: znachok_bmw
description: Заливка картинок/анимаций на круглый дисплей-логотип по Bluetooth (BLE).
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_blue_plus: ^1.32.12   # BLE
  file_picker: ^10.3.7          # выбор GIF/файлов из хранилища
  image_picker: ^1.1.2          # выбор фото/камера
  image: ^4.2.0                 # ресайз/маска/GIF -> RGB565
  permission_handler: ^11.3.1   # рантайм-разрешения BLE (Android 12+)

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
